USE gamehub_ads;

ALTER TABLE games ADD COLUMN IF NOT EXISTS slug VARCHAR(160) NULL UNIQUE;
ALTER TABLE games ADD COLUMN IF NOT EXISTS category VARCHAR(80) NOT NULL DEFAULT 'Arcade';
ALTER TABLE games ADD COLUMN IF NOT EXISTS rating DECIMAL(2,1) NOT NULL DEFAULT 0.0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS thumbnail_url TEXT NULL;
ALTER TABLE games ADD COLUMN IF NOT EXISTS description TEXT NULL;
ALTER TABLE games ADD COLUMN IF NOT EXISTS tags JSON NULL;
ALTER TABLE games ADD COLUMN IF NOT EXISTS badge VARCHAR(40) NULL;
ALTER TABLE games ADD COLUMN IF NOT EXISTS game_url TEXT NULL;
ALTER TABLE games ADD COLUMN IF NOT EXISTS plays BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT FALSE;
UPDATE games SET slug=game_id WHERE slug IS NULL;