USE gamehub_ads;

INSERT INTO games (game_id, slug, name, category, rating, thumbnail_url, description, tags, badge, game_url, plays, featured, status)
VALUES
('demo-game-001', 'demo', 'Super Cube Jump', 'Arcade', 4.8, 'https://images.unsplash.com/photo-1614294148960-9aa740632a87?auto=format&fit=crop&w=900&q=85', 'Jump, dodge and beat your high score in this fast arcade challenge.', '["Arcade","Jumping","Casual"]', 'Featured', '/games/demo/index.html', 12405, TRUE, 'active'),
('racing-fury', 'racing-fury', 'Racing Fury', 'Racing', 4.5, 'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=900&q=85', 'Take the inside line, drift through traffic and own the finish line.', '["Racing","Cars","Driving"]', NULL, '/games/demo/index.html', 8300, FALSE, 'active'),
('puzzle-master', 'puzzle-master', 'Puzzle Master', 'Puzzle', 4.2, 'https://images.unsplash.com/photo-1553481187-be93c21490a9?auto=format&fit=crop&w=900&q=85', 'A clean, clever brain teaser with satisfying puzzles around every corner.', '["Puzzle","Brain","Casual"]', NULL, '/games/demo/index.html', 6200, FALSE, 'active'),
('zombie-shooter', 'zombie-shooter', 'Zombie Shooter', 'Action', 4.7, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=900&q=85', 'Keep moving, line up your shots and survive the endless night.', '["Action","Shooting","Adventure"]', 'New', '/games/demo/index.html', 10400, FALSE, 'active'),
('sky-high', 'sky-high', 'Sky High', 'Casual', 4.3, 'https://images.unsplash.com/photo-1539635278303-d4002c07eae3?auto=format&fit=crop&w=900&q=85', 'Climb above the clouds and see how far your timing can take you.', '["Casual","Adventure","Skill"]', NULL, '/games/demo/index.html', 5100, FALSE, 'active'),
('drift-king', 'drift-king', 'Drift King', 'Racing', 4.9, 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=85', 'Burn rubber, chain perfect drifts and become the king of the track.', '["Racing","Cars","Sports"]', 'Hot', '/games/demo/index.html', 15100, FALSE, 'active')
ON DUPLICATE KEY UPDATE slug=VALUES(slug), name=VALUES(name), category=VALUES(category), rating=VALUES(rating), thumbnail_url=VALUES(thumbnail_url), description=VALUES(description), tags=VALUES(tags), badge=VALUES(badge), game_url=VALUES(game_url), plays=VALUES(plays), featured=VALUES(featured), status=VALUES(status);